version: "3.9"

services:
  database:
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
      POSTGRES_DB: "dev"
    ports:
      - "5432:5432"
    volumes:
      - db:/data/postgres

volumes:
  db:
